-- FinTrack - Supabase/PostgreSQL
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    description text not null,
    amount numeric(12,2) not null check (amount > 0),
    type text not null check (type in ('Receita', 'Despesa')),
    category text not null,
    date date not null,
    created_at timestamptz not null default now()
);

create table if not exists public.savings_goals (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    target_amount numeric(12,2) not null check (target_amount > 0),
    deadline date,
    created_at timestamptz not null default now()
);

create table if not exists public.savings_transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    goal_id bigint not null references public.savings_goals(id) on delete cascade,
    amount numeric(12,2) not null check (amount > 0),
    movement_type text not null check (movement_type in ('Depósito', 'Retirada')),
    date date not null,
    created_at timestamptz not null default now()
);

create index if not exists transactions_user_id_idx
    on public.transactions(user_id);

create index if not exists savings_goals_user_id_idx
    on public.savings_goals(user_id);

create index if not exists savings_transactions_user_id_idx
    on public.savings_transactions(user_id);

create index if not exists savings_transactions_goal_id_idx
    on public.savings_transactions(goal_id);

alter table public.transactions enable row level security;
alter table public.savings_goals enable row level security;
alter table public.savings_transactions enable row level security;

revoke all on table public.transactions from anon, authenticated;
revoke all on table public.savings_goals from anon, authenticated;
revoke all on table public.savings_transactions from anon, authenticated;

grant select, insert, update, delete on table public.transactions to authenticated;
grant select, insert, update, delete on table public.savings_goals to authenticated;
grant select, insert, update, delete on table public.savings_transactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own"
on public.transactions for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "transactions_insert_own" on public.transactions;
create policy "transactions_insert_own"
on public.transactions for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "transactions_update_own" on public.transactions;
create policy "transactions_update_own"
on public.transactions for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "transactions_delete_own" on public.transactions;
create policy "transactions_delete_own"
on public.transactions for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "goals_select_own" on public.savings_goals;
create policy "goals_select_own"
on public.savings_goals for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "goals_insert_own" on public.savings_goals;
create policy "goals_insert_own"
on public.savings_goals for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "goals_update_own" on public.savings_goals;
create policy "goals_update_own"
on public.savings_goals for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "goals_delete_own" on public.savings_goals;
create policy "goals_delete_own"
on public.savings_goals for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "saving_tx_select_own" on public.savings_transactions;
create policy "saving_tx_select_own"
on public.savings_transactions for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "saving_tx_insert_own" on public.savings_transactions;
create policy "saving_tx_insert_own"
on public.savings_transactions for insert to authenticated
with check (
    (select auth.uid()) = user_id
    and exists (
        select 1 from public.savings_goals g
        where g.id = goal_id
          and g.user_id = (select auth.uid())
    )
);

drop policy if exists "saving_tx_delete_own" on public.savings_transactions;
create policy "saving_tx_delete_own"
on public.savings_transactions for delete to authenticated
using ((select auth.uid()) = user_id);
